site_name: CANFAR Deployments
site_url: https://www.opencadc.org/deployments/
site_author: CANFAR
site_description: Deployment automation, Helm charts, and operations guidance for the CANFAR platform.
repo_url: https://github.com/opencadc/deployments/
repo_name: opencadc/deployments
edit_uri: blob/main/docs/
remote_branch: gh-pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opencadc
      name: CANFAR on GitHub
    - icon: fontawesome/brands/docker
      link: https://images.canfar.net
      name: Harbor Registry
    - icon: fontawesome/solid/envelope
      link: mailto:support@canfar.net
      name: Email Support

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: canfar
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.instant.prefetch
    - toc.follow
    - navigation.top
    - announce.dismiss
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: timeago
      timezone: America/Vancouver
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
      toc_depth: 2
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: opencadc
      repo: deployments
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Operations:
    - operations/index.md
    - CI/CD Pipelines: operations/ci-cd.md
    - Release Process: operations/release-process.md
