{
 "title": "Kueue Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cluster Wide Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{namespace!=\"\"}[$__rate_interval])))",
     "legendFormat": "Pod CPU Usage"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster CPU Limit" },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace!=\"\",resource=\"cpu\"})",
     "legendFormat": "Pod CPU Requested"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Cluster Mem Limit"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace!=\"\", container!=\"\"})",
     "legendFormat": "Pod Mem Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", namespace!=\"\"})",
     "legendFormat": "Pod Mem Requested"
    }
   ]
  },
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Lifecycle Phase",
   "type": "timeseries",
   "description": "Pending: The Pod has been accepted by the Kubernetes cluster, but one or more of the containers has not been set up and made ready to run. This includes time a Pod spends waiting to be scheduled as well as the time spent downloading container images over the network.\n\nRunning: The Pod has been bound to a node, and all of the containers have been created. At least one container is still running, or is in the process of starting or restarting.\n\nSucceeded: All containers in the Pod have terminated in success, and will not be restarted.\n\nFailed: All containers in the Pod have terminated, and at least one container has terminated in failure. That is, the container either exited with non-zero status or was terminated by the system, and is not set for automatic restarting.\n\nUnknown: For some reason the state of the Pod could not be obtained. This phase typically occurs due to an error in communicating with the node where the Pod should be running.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{namespace=~\"skaha-workload|canfar-b-workload\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kueue Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Admissions / Second",
   "type": "stat",
   "description": "The total number of attempts to admit workloads. Each admission attempt might try to admit more than one workload.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kueue_admission_attempts_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Latency [99th Percentile]",
   "type": "stat",
   "description": "The latency of an admission attempt.",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(kueue_admission_attempt_duration_seconds_bucket[$__interval]))>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission Latency [75th Percentile]",
   "type": "stat",
   "description": "The latency of an admission attempt.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.75, rate(kueue_admission_attempt_duration_seconds_bucket[$__interval]))>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "stat",
   "description": "The total number of all active workloads in all cluster queues",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_admitted_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending workloads",
   "type": "stat",
   "description": "The total number of all pending workloads in all cluster queues",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kueue_pending_workloads)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cluster Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Active Workloads per ClusterQueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(cluster_queue)(kueue_admitted_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Workloads per ClusterQueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum by(cluster_queue)(kueue_pending_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Local Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(name) (kueue_local_queue_resource_usage{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kueue_local_queue_resource_usage{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Workloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kueue_local_queue_pending_workloads)",
     "legendFormat": "Pending Workloads: {{exported_namespace}}"
    }
   ]
  },
  {
   "title": "Active Workloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kueue_local_queue_admitted_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reserving Active Workloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kueue_local_queue_reserving_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "The total number of nodes in a cluster",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 74 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})",
     "legendFormat": "Not Ready"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})/(sum(kube_node_status_allocatable{resource=\"memory\"}))",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "CPU Requested"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "stat",
   "description": "The total number of nodes that can't schedule PODs",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Disk Pressure",
   "type": "stat",
   "description": "The total number of nodes with DiskPressure condition",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Mem Pressure",
   "type": "stat",
   "description": "The total number of nodes with MemPressure condition",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes PID Pressure",
   "type": "stat",
   "description": "The total number of nodes with PIDPressure condition",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}